version: 2.1

executors:
  base-gcp-img:
    docker:
      - image: cimg/gcp:2025.01
    working_directory: ~/repo

  base-python-img:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/repo

commands:
  setup-docker:
    steps:
      - checkout
      - setup_remote_docker

  run-script:
    parameters:
      script_path:
        type: string
    steps:
      - run:
          name: Run Script << parameters.script_path >>
          command: sh << parameters.script_path >>

jobs:
  create_repositories:
    executor: base-gcp-img
    steps:
      - checkout
      - run-script:
          script_path: ./build-scripts/auth_gcp.sh
      - run-script:
          script_path: ./build-scripts/artifact_reg.sh

  build_push_img:
    executor: base-gcp-img
    steps:
      - setup-docker
      - run-script:
          script_path: ./build-scripts/auth_gcp.sh
      - run-script:
          script_path: ./build-scripts/build_containers.sh
      - run-script:
          script_path: ./build-scripts/push_containers.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    executor: base-python-img
    steps:
      - checkout
      - run:
          name: install dependencies
          command: sh ./build-scripts/install_packages.sh

  gcp-cli:
    executor: base-gcp-img
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud
          command: sh ./build-scripts/auth_gcp.sh
      - run:
          name: deploy google cloud function
          command: sh ./build-scripts/deploy_function.sh


workflows:
  build_and_deploy:
    jobs:
      - approve-pipeline:
          type: approval

      - build:
          name: Install-Python-Libraries
          requires:
            - approve-pipeline

      - gcp-cli:
          name: Authenticate-And-Deploy-Function
          context:
            - Spotify_ETL
          requires:
            - Install-Python-Libraries