version: 2.1

executors:
  base-gcp-img:
    docker:
      - image: cimg/gcp:2025.01
    working_directory: ~/repo

  base-python-img:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/repo

commands:
  setup-docker:
    steps:
      - checkout
      - setup_remote_docker

  run-script:
    parameters:
      script_path:
        type: string
    steps:
      - run:
          name: Run Script << parameters.script_path >>
          command: sh << parameters.script_path >>

jobs:
  create_repositories:
    executor: base-gcp-img
    steps:
      - checkout
      - run-script:
          script_path: ./build-scripts/auth_gcp.sh
      - run-script:
          script_path: ./build-scripts/artifact_reg.sh

  build_push_img:
    executor: base-gcp-img
    steps:
      - setup-docker
      - run-script:
          script_path: ./build-scripts/auth_gcp.sh
      - run-script:
          script_path: ./build-scripts/build_containers.sh
      - run-script:
          script_path: ./build-scripts/push_containers.sh
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_sp_extractor:
    executor: base-gcp-img
    steps:
      - attach_workspace:
          at: .
      - setup-docker
      - run-script:
          script_path: ./build/auth_gcp.sh
      - run-script:
          script_path: ./build/deploy_sp_extractor.sh

  install-python:
    executor: base-python-img
    steps:
      - checkout
      - run:
          name: install dependencies
          command: sh ./build-scripts/install_packages.sh

  deploy-function:
    executor: base-gcp-img
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud
          command: sh ./build-scripts/auth_gcp.sh
      - run:
          name: deploy google cloud function
          command: sh ./build-scripts/deploy_function.sh


workflows:
  build_and_deploy:
    jobs:
      - approve-pipeline:
          type: approval

      - create_repositories:
          name: create-repositories
          context:
            - Spotify_ETL
          requires:
            - approve-pipeline

      - build_push_img:
          name: build-push-img
          context:
            - Spotify_ETL
          requires:
            - create-repositories

      - deploy_sp_extractor:
          name: deploy_sp_extractor
          context:
            - Spotify_ETL
          requires:
            - build-push-img

      - install-python:
          name: Install Python Libraries
          requires:
            - approve-pipeline

      - deploy-function:
          name: Authenticate And Deploy Function
          context:
            - Spotify_ETL
          requires:
            - Install-Python-Libraries